#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Services/Catalog/Catalog.Grpc/Catalog.Grpc.csproj", "Services/Catalog/Catalog.Grpc/"]
COPY ["Services/Catalog/Catalog.Infrastructure/Catalog.Infrastructure.csproj", "Services/Catalog/Catalog.Infrastructure/"]
COPY ["Services/Catalog/Catalog.Domain/Catalog.Domain.csproj", "Services/Catalog/Catalog.Domain/"]
RUN dotnet restore "Services/Catalog/Catalog.Grpc/Catalog.Grpc.csproj"
COPY . .
WORKDIR "/src/Services/Catalog/Catalog.Grpc"
RUN dotnet build "Catalog.Grpc.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Catalog.Grpc.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Catalog.Grpc.dll"]
