version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalog.grpc:
    image: ${DOCKER_REGISTRY-}cataloggrpc
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Grpc/Dockerfile


  checkout.api:
    image: ${DOCKER_REGISTRY-}checkoutapi
    build:
      context: .
      dockerfile: Services/Checkout/Checkout.API/Dockerfile

